-- SCHEMA: list

-- DROP SCHEMA IF EXISTS list ;
--Crear schema list
CREATE SCHEMA IF NOT EXISTS list
    AUTHORIZATION jeyfredc;

-- Table: list.tv_shows

-- DROP TABLE IF EXISTS list.tv_shows;

-- Crear tabla tv_shows
CREATE TABLE IF NOT EXISTS list.tv_shows
(
    id integer NOT NULL DEFAULT nextval('list.tv_shows_id_seq'::regclass),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    program_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    images_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    images_width integer NOT NULL,
    images_height integer NOT NULL,
    release_year integer NOT NULL,
    CONSTRAINT tv_shows_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS list.tv_shows
    OWNER to jeyfredc;

-- Insertar valores del archivo json

INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Wolf Creek','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/128/61/12861-PosterArt-ec32a81986a45eac7e080112075ab466.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('No Activity','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/106/36/10636-PosterArt-9add943c5e62c2d89f6d31458d33508a.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Billions','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/117/25/11725-PosterArt-deecf8dbd786dfa2d964413b0bf83726.jpg',720,1080,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Better Call Saul','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/175/7/1757-PosterArt-fc0e2a5b18d4a662717f3cbb1827871d.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Younger','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/143/24/14324-PosterArt-a0168953a3b93681dbd60c7bcc50a0af.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Ash vs Evil Dead','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/102/56/10256-PosterArt-1a57bf03033531becb18f2ad0c755f5a.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Transparent','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/108/7/1087-PosterArt-d19ff1330226ba26e4eb1def7a465f99.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Power','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/512/1/5121-PosterArt-8957df8b3f89afc2809d068a9bf7f667.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('UnREAL','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/939/3/9393-PosterArt-6e5b82950cfce05fef0a50ff7a69474a.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Last Ship','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/197/7/1977-PosterArt-a2d3a9bb0ba1e05d26b29aed143715ce.jpg',500,750,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Girlfriend Experience','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/128/54/12854-PosterArt-683f17d4770e2f0febab93cf251bb1ee.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('11.22.63','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/120/40/12040-PosterArt-2a08532d986336771ea5a70658b6a957.jpg',400,600,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Roadies','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/132/42/13242-PosterArt-dfd9c3a0fa5db6e2e38b62e7fedcaf47.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Sherlock: The Abominable Bride','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/115/93/11593-PosterArt-33274b61ab0cb0e19cb7bff35824efb9.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('iZombie','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/197/5/1975-PosterArt-5c0ac7935dfb577df222814c2fbc1edb.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Containment','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/129/01/12901-PosterArt-b18cb05ecda13ea274c4e32a2d6ea427.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Flesh and Bone','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/102/57/10257-PosterArt-5846b1f514837b29477d566df3f713d2.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Circus: Inside The Greatest Political Show On Earth','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/133/40/13340-PosterArt-f5edb5d566e3d5375d7caad82e7839f5.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Community','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/109/3/1093-PosterArt-69b57818da7152ce84d22dc72513ae4e.jpg',1000,1500,2009);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Mozart in the Jungle','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/144/8/1448-PosterArt-0b4461ee688948ab6efa1ff2d22220df.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Blunt Talk','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/127/71/12771-PosterArt-d79951a3a8662abf816e6446c2b725e0.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Angie Tribeca','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/131/66/13166-PosterArt-d2a89999fa2d84015ba82a979e0ed796.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Deutschland 83','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/108/40/10840-PosterArt-a2fe05c4a0e1fdec049c8a35f8cd26a1.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Dice','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/128/02/12802-PosterArt-e0890393f2bf08c3da51479626c45134.jpeg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Billy & Billie','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/108/68/10868-PosterArt-84217c5c12e1d8747873d4ca916fbad5.jpg',1000,1500,0);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Mad Dogs','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/127/72/12772-PosterArt-4217136f78c400592a91cb7a2f4f4bd6.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Gay for Play Game Show Starring RuPaul','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/143/61/14361-PosterArt-db21d9a7cd3362d1d9069d7c1d9aa554.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Acquitted','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/108/70/10870-PosterArt-c37e8232f327b27bc62043ea627ca528.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Following','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/197/3/1973-PosterArt-356d876eeca0713c592053c6283aa254.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('U2: Live in Paris','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/963/194/963194-PosterArt-9d1f4f28bb94e5e0f06e83d1216a8e30.jpg',559,828,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Trollied','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/173/2/1732-PosterArt-85cc2547b4aca4a5dd38e332f602a3c3.jpg',1000,1500,2011);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Gigolos','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/120/08/12008-PosterArt-fd5ad91e4054960b00e45e6d63b0c3c9.jpeg',720,1080,2011);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Significant Mother','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/144/42/14442-PosterArt-26b21287841c80c0cafa1a668b5c747d.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Under The Gun','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/115/3873/1153873-PosterArt-93b3333a696042bf7da06b874af771d8.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Lost Girl','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/109/2/1092-PosterArt-c79b7c95666d7792a3c60e4407962f81.jpg',1000,1500,2010);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Plonk','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/192/3/1923-PosterArt-f4aba43064f61d1668840c4d0df91565.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Eye Candy','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/108/72/10872-PosterArt-25f67e1932dffe23acee016241ef2610.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('HAPPYish','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/119/98/11998-PosterArt-c937329b04129ead97d0503818b5e54a.jpg',720,1080,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Friends','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/198/3/1983-PosterArt-53b54be2659ca7905f56d67f6f3df803.jpg',550,825,1994);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Mad Max: Fury Road','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/958/725/958725-PosterArt-96c5bbb6e15269f5b5cd9bc7801de1d9.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Twin Peaks','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/167/0/1670-PosterArt-9b61ff8d9260436f911665f1312742bd.jpg',500,750,1990);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Hunger Games','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/843/787/843787-PosterArt-dafc8872838e5d0f806c895b62134021.jpg',800,1200,2012);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Hunger Games: Catching Fire','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/843/788/843788-PosterArt-b4e53eeb7e3e560a93c4033f3c791945.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Hunger Games: Mockingjay - Part 1','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/376/199/376199-PosterArt-0929f0c32637703dc8ba857e81154bc9.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Hunger Games: Mockingjay - Part 2','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/109/8333/1098333-PosterArt-c72002fd42ec6f2cfc53004a59b432be.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Frasier','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/120/27/12027-PosterArt-3f8c0625d76d30c9a583c647e4c29c67.jpg',1000,1500,1994);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('San Andreas','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/958/726/958726-PosterArt-46061b8e3d5b4c8fd690d045ee524d0f.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Dexter','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/160/6/1606-PosterArt-8de75e6dae6678b82aa5093f204931aa.jpg',671,1007,2006);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Paper Planes','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/376/206/376206-PosterArt-fc212c3beeab2c066977541a2312d732.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Beauty and the Beast','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/139/76/13976-PosterArt-6d33e74aa9ec685bf96a3e692521c3ae.jpg',1000,1500,2012);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Seinfeld','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/156/39/15639-PosterArt-4f0ab756eab01a0805b7bed4601b96ec.jpg',1000,1500,1989);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Self/less','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/103/5943/1035943-PosterArt-24bf05e844865af039feafa36f0a87bd.jpg',1400,2100,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Fringe','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/198/4/1984-PosterArt-284e8c935ea5f69e62fc1fc8bd17343f.jpg',1000,1500,2008);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('How to Lose a Guy in 10 Days','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/382/999/98fe3aee68fff2ce6e008019c789e22e.jpg',700,1050,2003);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('RuPaul''s Drag Race','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/915/4/9154-PosterArt-140aeb530d9e317778581855d31459db.jpg',1000,1500,0);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Time Traveler''s Wife','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/418/042/d8548579cfa853a7c5bc8f155790a310.jpg',1000,1500,2008);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Nanny','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/110/0/1100-PosterArt-28bef45866329f97901766f213b145ea.jpg',1000,1500,1993);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Best of Me','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/376/200/376200-PosterArt-0d02eaf47c7a9b050909420eb81ff569.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Case Of: JonBenet Ramsey','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/160/33/16033-PosterArt-3106fcae6ce5fbe338bc3ae82fc42b25.jpg',1000,1500,2016);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('American Sniper','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/952/708/952708-PosterArt-d3beb37b66819c3f6281d7accc3020d6.jpg',1400,2100,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Geordie Shore','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/153/7/1537-PosterArt-57cb90d82c7f6a6b0c69752059c66e5b.jpg',800,1200,2011);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Victoria','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/119/2937/1192937-PosterArt-2f0c0a5bfaec9ce6e2662283f9c660b2.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Sicario','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/105/3102/1053102-PosterArt-54c83e37dfc1500b61ac3f37b3e062a4.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Hey Duggee','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/125/42/12542-PosterArt-4290c6751c88bc2384169dda62934e34.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('John Wick','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/376/201/376201-PosterArt-4f91ac739ae5147a51ae3abc78d55f2d.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Freakonomics','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/371/739/371739-PosterArt-ba6bb08bb67b565aaa35ba59e15bdf7d.jpg',1000,1500,2009);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Troll Hunter','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/393/966/393966-PosterArt-72da04b296c0796a20540205eaa4fce0.jpg',500,750,2011);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Spooks: The Greater Good','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/119/3835/1193835-PosterArt-faaba78b86d44c352d258d7189d485f6.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Inside The Human Body','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/128/10/12810-PosterArt-a3db21e3417f03062e9841da391ae8cc.jpg',1000,1500,0);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Being Erica','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/100/3/1003-PosterArt-c9a263c56c91eb3e58a5e073e020c566.jpg',1024,1536,2009);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Jenny''s Wedding','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/103/5939/1035939-PosterArt-8513e9e2dcfc6845adbd6d1fdd1a5f5f.jpg',1400,2100,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Ringer','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/122/87/12287-PosterArt-19484385f08dd0d6b334779512c494a3.jpg',1000,1500,2011);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Life of Crime','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/118/0648/1180648-PosterArt-80d56bbb6635cff7a49ad2287711c378.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Carrie Diaries','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/198/9/1989-PosterArt-0aaf7d4d4d1014e393671c1c08365946.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Drop Dead Diva','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/392/315/c90b83dbe5270d6560d0b908aa2090cf.jpg',720,1080,2009);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Leon: The Professional','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/119/3838/1193838-PosterArt-7328f58d3e64953a540a3543a5cd5c39.jpg',1000,1500,1994);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('A Lego Brickumentary','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/109/8345/1098345-PosterArt-f0f207e02947ca76d9f9b238aea54dc1.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Inbetweeners','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/200/0/2000-PosterArt-835be2285f9301293d380db580f8ad96.jpg',1000,1500,2008);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Just Friends','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/375/664/375664-PosterArt-d11924fb0752525039b1168197030753.jpg',500,750,2005);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Ernest & Celestine','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/928/838/928838-PosterArt-c3d8ac708b712062e519a3b106469595.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Star Trek: Deep Space Nine','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/160/3/1603-PosterArt-53b8c03e1244053c1c58905dd6738e24.jpg',1001,1501,1993);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Valiant','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/885/233/885233-PosterArt-e79ac1b3fbb5f8677094f5ae8adca301.jpg',1000,1500,2005);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The LA Complex','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/115/38/11538-PosterArt-3fa112d2e653653fcfc9fe39b34ae1df.jpg',1000,1500,2012);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Hannibal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/109/1/1091-PosterArt-bbcf03acc18eebfc343754b05f39738f.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Voices','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/103/5938/1035938-PosterArt-4131ef088343f85d686806f2b80253c1.jpg',1400,2100,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Sex and the City 2','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/328/010/092e34afe0648a42cf12beb2d7557a65.jpg',500,750,2009);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Nasty Baby','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/110/1174/1101174-PosterArt-c1fe5d416b9e410b8726893272e8711a.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Tracers','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/958/724/958724-PosterArt-28f056d80c744f0ca9418250db9e4c61.jpg',1000,1500,2015);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Shield','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/109/8/1098-PosterArt-5f2fbc7f02c02a525ab9f3e95008f3fc.jpg',1000,1500,2002);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Review With Forrest MacNeil','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/126/88/12688-PosterArt-e8b36ef2902246538b9bbfdc380e5a3a.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('I Am Legend','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/375/797/375797-PosterArt-f456379f7c61bcd9c8f9fc781f4bce28.jpg',1000,1500,2008);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('At Home With Julia','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/120/28/12028-PosterArt-0c087d1f4f12d21cda838f53cba2c8a5.jpg',720,1080,0);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('American Dreams','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/971/6/9716-PosterArt-d7983da60a5d146f87f0bf5b4939727a.jpg',1000,1500,2002);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('How To Train Your Dragon','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/110/1196/1101196-PosterArt-c47d98ddca64ef18cf79c78d6ab8b3ad.jpg',1000,1500,2010);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Star Trek: Enterprise','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/120/02/12002-PosterArt-90648d08f69e94d44d6cb4de2cdda757.jpg',1000,1500,0);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Ages Of Love','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/372/670/372670-PosterArt-0c1d61510fdf59ff32299038e669db44.jpg',350,525,2010);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Prisoners','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/408/331/408331-PosterArt-75cb706fded100b4f28cc6b1a007fc1c.jpg',1000,1500,2013);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Almost Royal','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/124/27/12427-PosterArt-92cd41fc035a71a5e5f6cc7569b4266e.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('Danny Collins','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','movie','https://streamcoimg-a.akamaihd.net/000/999/667/999667-PosterArt-65e6f88ede8bdcdad6d4d4f1549936ee.jpg',1000,1500,2014);
INSERT INTO list.tv_shows(title,description,program_type,images_url,images_width,images_height,release_year) VALUES ('The Wrong Mans','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.','series','https://streamcoimg-a.akamaihd.net/000/124/31/12431-PosterArt-f7d91329c70a7fa206e838423caa31bd.jpg',1000,1500,2013);
